CREATE TABLE DISCUSSION(
    DISCUSSION_ID INT PRIMARY KEY AUTO_INCREMENT,
    DISCUSSION_NAME VARCHAR(32),
    USER1 INT,
    USER2 INT,
    FOREIGN KEY(USER1) REFERENCES ACCOUNT(USER_ID),
    FOREIGN KEY(USER2) REFERENCES ACCOUNT(USER_ID)
);