CREATE TABLE JOIN_REQUEST(
    USER_ID INT,
    EVENT_ID INT,
    PRIMARY KEY (USER_ID, EVENT_ID),
    FOREIGN KEY (USER_ID) REFERENCES ACCOUNT (USER_ID),
    FOREIGN KEY (EVENT_ID) REFERENCES EVENT (EVENT_ID)
);