DROP TABLE COMPETITOR;

CREATE TABLE COMPETITOR(
    EVENT_ID INT,
    USER_ID INT,
    JOIN_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (EVENT_ID, USER_ID),
    FOREIGN KEY (EVENT_ID) REFERENCES EVENT (EVENT_ID),
    FOREIGN KEY (USER_ID) REFERENCES ACCOUNT (USER_ID)
);