CREATE TABLE FRIEND_REQUEST(
    REQUESTER INT,
    TARGET INT,
    FOREIGN KEY (REQUESTER) REFERENCES ACCOUNT(USER_ID),
    FOREIGN KEY (TARGET) REFERENCES ACCOUNT(USER_ID),
    PRIMARY KEY (REQUESTER, TARGET)
);