CREATE OR REPLACE VIEW EVENT_FLUX AS
SELECT 
    'JOIN' AS FLUX_TYPE, 
    C.USER_ID AS SENDER_ID, 
    PSEUDO AS SENDER_NAME,
    C.EVENT_ID AS TARGET_ID, 
    EVENT_NAME AS TARGET_NAME,
    NULL AS FLUX_DATA, 
    UNIX_TIMESTAMP(JOIN_DATE) AS FLUX_DATE 
    FROM COMPETITOR C
    JOIN ACCOUNT A ON C.USER_ID = A.USER_ID
    JOIN EVENT E ON E.EVENT_ID = C.EVENT_ID
UNION
SELECT 
    'MESSAGE' AS FLUX_TYPE, 
    M.USER_ID AS SENDER_ID, 
    PSEUDO AS SENDER_NAME,
    M.EVENT_ID AS TARGET_ID, 
    EVENT_NAME AS TARGET_NAME,
    MESSAGE AS FLUX_DATA, 
    UNIX_TIMESTAMP(EVENT_MESSAGE_DATE) AS FLUX_DATE 
    FROM EVENT_MESSAGE M
    JOIN ACCOUNT A ON A.USER_ID = M.USER_ID
    JOIN EVENT E ON E.EVENT_ID = M.EVENT_ID
UNION 
SELECT 
    'EVENTCREATE' AS FLUX_TYPE, 
    ORGANIZER AS SENDER_ID, 
    PSEUDO AS SENDER_NAME,
    EVENT_ID AS TARGET_ID, 
    EVENT_NAME AS TARGET_NAME,
    NULL AS FLUAX_DATA, 
    UNIX_TIMESTAMP(EVENT_DATE) AS FLUX_DATE 
    FROM EVENT
    JOIN ACCOUNT ON USER_ID = ORGANIZER
ORDER BY FLUX_DATE DESC;

CREATE OR REPLACE VIEW ACCOUNT_FLUX AS
SELECT * FROM EVENT_FLUX WHERE FLUX_TYPE IN('JOIN', 'EVENTCREATE')
UNION
SELECT 
    'FRIEND' AS FLUX_TYPE, 
    USER1 AS SENDER_ID, 
    A1.PSEUDO AS SENDER_NAME,
    USER2 AS TARGET_ID, 
    A2.PSEUDO AS TARGET_NAME,
    NULL AS FLUX_DATA, 
    UNIX_TIMESTAMP(FRIEND_DATE) AS FLUX_DATE 
    FROM FRIEND F
    JOIN ACCOUNT A1 ON F.USER1 = A1.USER_ID
    JOIN ACCOUNT A2 ON F.USER2 = A2.USER_ID
UNION
SELECT 
    'FRIEND' AS FLUX_TYPE, 
    USER2 AS SENDER_ID, 
    A2.PSEUDO AS SENDER_NAME,
    USER1 AS TARGET_ID, 
    A1.PSEUDO AS TARGET_NAME,
    NULL AS FLUX_DATA, 
    UNIX_TIMESTAMP(FRIEND_DATE) AS FLUX_DATE 
    FROM FRIEND F
    JOIN ACCOUNT A1 ON F.USER1 = A1.USER_ID
    JOIN ACCOUNT A2 ON F.USER2 = A2.USER_ID
UNION
SELECT 
    'INSCRIPTION' AS FLUX_TYPE, 
    USER_ID AS SENDER_ID, 
    PSEUDO AS SENDER_NAME,
    NULL AS TARGET_ID, 
    NULL AS TARGET_NAME,
    NULL AS FLUX_DATA, 
    UNIX_TIMESTAMP(INSCRIPTION_DATE) AS FLUX_DATE 
    FROM ACCOUNT
ORDER BY FLUX_DATE DESC;