CREATE TABLE EVENT_MESSAGE(
    EVENT_ID INT,
    USER_ID INT,
    EVENT_MESSAGE_ID INT PRIMARY KEY AUTO_INCREMENT,
    MESSAGE VARCHAR(128),
    EVENT_MESSAGE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (EVENT_ID) REFERENCES EVENT (EVENT_ID),
    FOREIGN KEY (USER_ID) REFERENCES ACCOUNT (USER_ID)
);

CREATE OR REPLACE VIEW EVENT_FLUX AS
SELECT 'JOIN' AS FLUX_TYPE, USER_ID AS SENDER, EVENT_ID AS TARGET, NULL AS FLUX_DATA, UNIX_TIMESTAMP(JOIN_DATE) AS FLUX_DATE FROM COMPETITOR
UNION
SELECT 'MESSAGE' AS FLUX_TYPE, USER_ID AS SENDER, EVENT_ID AS TARGET, MESSAGE AS FLUX_DATA, UNIX_TIMESTAMP(EVENT_MESSAGE_DATE) AS FLUX_DATE FROM EVENT_MESSAGE
UNION 
SELECT 'EVENTCREATE' AS FLUX_TYPE, ORGANIZER AS SENDER, EVENT_ID AS TARGET, NULL AS FLUAX_DATA, UNIX_TIMESTAMP(EVENT_DATE) AS FLUX_DATE FROM EVENT
ORDER BY FLUX_DATE DESC;